import Link from 'next/link';
import { Header } from '../components/Header.tsx';
import { allPaths, pendingReview, snapshotMeta } from '../lib/content.ts';

const RISK_LABEL: Record<string, string> = {
  low: 'Auto-published',
  medium: 'Sampled for review',
  high: 'Human approval required',
};

export default function Home() {
  const paths = allPaths();
  const pending = pendingReview();
  const meta = snapshotMeta();

  return (
    <main>
      <Header />

      <section className="py-10">
        <h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">
          Any source, turned into a path you can finish.
        </h1>
        <p className="mt-3 max-w-xl text-ink-soft">
          Including the things invented last week. Every lesson cites the source it rests
          on, every path is ordered by what you need first, and practice comes back before
          you forget it.
        </p>
      </section>

      <section>
        <h2 className="text-sm font-medium uppercase tracking-wide text-ink-soft">
          Paths
        </h2>
        <ul className="mt-3 space-y-3">
          {paths.map((p) => (
            <li key={p.id}>
              <Link
                href={`/path/${p.slug}`}
                className="block rounded-lg border border-border bg-surface p-5 transition hover:border-accent"
              >
                <div className="flex items-baseline justify-between gap-3">
                  <p className="text-xs text-ink-soft">{p.domainTitle}</p>
                  <p className="shrink-0 text-xs text-ink-soft">{RISK_LABEL[p.riskTier]}</p>
                </div>
                <p className="mt-1 font-medium">{p.title}</p>
                <p className="mt-1 text-sm text-ink-soft">{p.summary}</p>
                <p className="mt-3 text-xs text-ink-soft">
                  {p.items.length} skills ·{' '}
                  {p.items.reduce((n, i) => n + i.estMinutes, 0)} min ·{' '}
                  {p.items.reduce((n, i) => n + i.exerciseCount, 0)} exercises
                </p>
              </Link>
            </li>
          ))}
        </ul>
      </section>

      {/* The publish gate, shown rather than hidden. Content a model approved but a
          human hasn't is NOT available — and saying so is the trust argument. */}
      {pending.length > 0 && (
        <section className="mt-10">
          <h2 className="text-sm font-medium uppercase tracking-wide text-ink-soft">
            Waiting on a human
          </h2>
          <ul className="mt-3 space-y-2">
            {pending.map((p) => (
              <li
                key={p.title}
                className="rounded-lg border border-warn/30 bg-warn-soft p-4 text-sm"
              >
                <p className="font-medium text-warn">{p.title}</p>
                <p className="mt-1 text-ink-soft">
                  {p.domainTitle} is high-risk, so {p.lessonCount} generated lessons are held
                  until a person with the subject knowledge approves them. Automated
                  verification passed; that isn&apos;t enough here.
                </p>
              </li>
            ))}
          </ul>
        </section>
      )}

      <footer className="mt-12 border-t border-border pt-4 text-xs text-ink-soft">
        <p>
          Content generated by the pipeline for ${meta.costUsd.toFixed(4)} ·{' '}
          {meta.reviewQueueSize} item{meta.reviewQueueSize === 1 ? '' : 's'} in the review
          queue
        </p>
        <p className="mt-1">
          Wave 0. Progress is stored in this browser only — no account, nothing uploaded.
        </p>
      </footer>
    </main>
  );
}
